### ISSUE TITLE
about how to predict sample

### ISSUE THREAD

**Issue by igorhuangchao** [rustandruin/spark-skylark-rfm-spectral-clustering#1]
I want use spectral clustering to predict some samples. but in the code i learn how to input data and make easy predict.  but now  i find i can't use the data what was normalizered . when i input Normalized data,the values of computerSVD has error. just like, my K equal 8 put into computerSVD then the output U  just have one component rather than 8 and the value was same . at  last i want know how much is the accuracy when run on your default data. thanks

**Comment by rustandruin** [comment]
This code has never been run! It was supposed to serve as a framework for later use, but I moved on to other projects. Sorry for the confusion.

**Comment by igorhuangchao** [comment]
thanks for you answer !   :)  It's ok .
